### ISSUE TITLE
Document MFA provider supporting multiple devices

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4648]
This is a cross-post of https://forge.typo3.org/issues/104312 to document at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Authentication/MultiFactorAuthentication.html#typo3-integration-and-api as own section how to provide support for mulitple devices

```yaml

  second-totp:
    class: TYPO3\CMS\Core\Authentication\Mfa\Provider\TotpProvider
    tags:
      - name: mfa.provider
        identifier: 'totp2'
        title: 'TOTP (backup)'
        description: 'LLL:EXT:core/Resources/Private/Language/locallang_mfa_provider.xlf:totp.description'
        setupInstructions: 'LLL:EXT:core/Resources/Private/Language/locallang_mfa_provider.xlf:totp.setupInstructions'
        icon: 'actions-qrcode'
        defaultProviderAllowed: true
        before: 'recovery-codes'
        after: 'totp'
```

talked to @liayn and it is ok to only document this option and not changing anything in the core
