### ISSUE TITLE
Linkbrowser, default classes removal

### ISSUE THREAD

**Issue by mpl-gyldendal** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#4788]
### Current behavior
When configuring the link browser to use default classes for page, url and file links, the classes are added to the link in CKEDITOR. When removing the link through the context menu or the link browser popup, the href attribute is removed but the class remains present and also the a tag.
The style itself is also not removeable by the styles plugin.

### Expected behavior/output
The class and tag should be removed

### TYPO3 versions
TYPO3 12, CKEDITOR 5

### UPDATE
If removing the link through context menu BEFORE SAVING, the tag and class is correctly removed. 

### Additional context
YAML configuration:
```
allowedTypes: "page,url,file"
allowedOptions: "target,title,class,params"
classesAnchor:
  - { class: "external-link", type: "url", target: "_blank" }
buttons:
  link:
    queryParametersSelector:
        enabled: true
    targetSelector:
      disabled: false
    properties:
      class:
        required: false
        allowedClasses: external-link
    url:
      properties:
        class:
          default: "external-link"
```

After insertion:
```
<p>
    This is an <a class="external-link" href="https://docs.typo3.org/">external link</a>.
</p>
```
After removal:
```
<p>
    This is an <a class="external-link">external</a> link.
</p>
```
