### ISSUE TITLE
Describe site setting variants

### ISSUE THREAD

**Issue by georgringer** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#5454]
Since v13, site settings can be used but currently it is a bit hard to understand those as yaml is hard to debug

2 working examples
```yaml
settings:
  foo.bar.baz:
    label: 'My example baz setting'
    description: 'Configure baz to be used in bar'
    type: color
    default: '#ccc'
  foo.bar.list:
    label: 'My example baz wrap'
    description: 'A stringlist'
    type: stringlist
    default: ['fo', 'bar2']
```

valid options can be found in code https://github.com/typo3/typo3/tree/a6498da2ed76230587218871e08176357fec39e5/typo3/sysext/core/Classes/Settings/Type
