### ISSUE TITLE
Yaml code block not valid in EventDispatcher

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#717]
You can see this if you build locally with Docker. The output is in warnings.txt

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Hooks/EventDispatcher/Index.html#registrating-the-event-listener

code block

```
services:
  MyCompany\MyPackage\EventListener\NullMailer:
    tags:
      - name: event.listener,
        identifier: 'myListener',
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent,
        before: 'redirects, anotherIdentifier'
```

This code block also does not validate with:

* pymentize (command line)
* online Yaml validator: https://codebeautify.org/yaml-validator

The comma on the end of the line sttarting with "identifier" is mared as wrong.

**Comment by sypets** [comment]
In the core, it is either:

[tags:
      - { name: event.listener,
          identifier: 'legacy-slot',
          event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent }](url)

or

```
tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileIndexRepositoryRecordCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent

```

**Comment by sypets** [comment]
This may look a little unintiuitive, but it is actually a map (key / value pair), consisting of "identifier", "method" and "event" inside a list item "name", see https://github.com/Animosity/CraftIRC/wiki/Complete-idiot's-introduction-to-yaml

More intuitive, if you add mor items:

```
tags:
      - listitem1: 'value'
        key1: 'value'
        key2: 'value'
     - listitem2: 'value: .
        key1: 'value'
         #  ...     
  
```
